### ISSUE TITLE
Zee5, hotstar, prime, Netflix & Voot 

### ISSUE THREAD

**Issue by ghost** [iWas-Coder/web-dl#2]
Zee5, hotstar, prime, Netflix & Voot needed...?
Can you give me your contact details

**Comment by iWas-Coder** [comment]
Hello! This project is still under active development, and the DRM decryption part is not there yet.

I do not know what specific issue you are having, so if you could post a description for each of the following fields it would be very useful to help diagnose your issue:
- **Issue description**
- **Environment**
- **Expected vs Actual behavior**
- **Steps to reproduce the issue**

This channel of communication is the preferred one. However, if you want to send me an email (**_wasymatieh01@gmail.com_**) you could do so.

Thanks.
