### ISSUE TITLE
Can you make as it is as for telegram bot with server?

### ISSUE THREAD

**Issue by ghost** [iWas-Coder/web-dl#4]
This will be working with the system not with a server and not working as a telegram bot so, can make another repository with telegram bot with server deploy support 🎁

**Comment by iWas-Coder** [comment]
If the question is about the licensing of the source code in this repository, it is all under the GPL-3.0 license. It is available for all readers under the `COPYING` file in the root of the repository.

In short, you can do whatever you want with the code, as the original license is mantained in all distributed and modified versions, keeping the intrinsec copyleft of this FOSS piece of software, watching out for all user's freedom.

Thank you.
